/*
 * Copyright (c) 2016, Huawei Technologies Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.openo.sdno.overlayvpndriver.model.vxlan.db;

import org.openo.sdno.overlayvpn.inventory.sdk.model.annotation.MOResType;
import org.openo.sdno.overlayvpn.model.uuid.AbstUuidModel;

/**
 * Class of VxLanExternalIdMapping Model Data. <br/>
 * <p>
 * It is used to recode the mapping between VxLan connection id that passed by caller and external
 * id that generated by controller.
 * </p>
 * 
 * @author
 * @version SDNO 0.5 July 12, 2016
 */
@MOResType(infoModelName = "vxlanexternalidmapping")
public class VxLanExternalIdMapping extends AbstUuidModel {

    private String vxLanInstanceId;

    private String externalId;

    private String deviceId;

    /**
     * Constructor.<br/>
     * 
     * @since SDNO 0.5
     */
    public VxLanExternalIdMapping() {
        super();
    }

    /**
     * Constructor<br/>
     *
     * @since SDNO 0.5
     * @param vxLanInstanceId UUID of VxLan instance
     * @param externalId UUID generated by controller
     * @param deviceId The UUID of device
     */
    public VxLanExternalIdMapping(String vxLanInstanceId, String externalId, String deviceId) {
        super();
        this.vxLanInstanceId = vxLanInstanceId;
        this.externalId = externalId;
        this.deviceId = deviceId;
    }

    public String getVxLanInstanceId() {
        return vxLanInstanceId;
    }

    public void setVxLanInstanceId(String vxLanInstanceId) {
        this.vxLanInstanceId = vxLanInstanceId;
    }

    public String getExternalId() {
        return externalId;
    }

    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
}
