/*
 * Copyright (c) 2016, Huawei Technologies Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.openo.sdno.overlayvpndriver.model.ipsec.db;

import org.openo.sdno.overlayvpn.inventory.sdk.model.annotation.MOResType;
import org.openo.sdno.overlayvpn.model.uuid.AbstUuidModel;

/**
 * Class of IpSecExternalIdMapping Model Data. <br/>
 * <p>
 * It is used to recode the mapping between IpSec connection id that passed by caller and external
 * id that generated by controller.
 * </p>
 * 
 * @author
 * @version SDNO 0.5 July 12, 2016
 */
@MOResType(infoModelName = "ipsecexternalidmapping")
public class IpSecExternalIdMapping extends AbstUuidModel {

    private String ipSecConnectionId;

    private String externalId;

    private String seqNumber;

    private String deviceId;

    /**
     * Constructor<br/>
     * 
     * @since SDNO 0.5
     */
    public IpSecExternalIdMapping() {
        // empty construction
        super();
    }

    /**
     * Constructor<br/>
     *
     * @since SDNO 0.5
     * @param ipSecConnectionId UUID of IpSec connection
     * @param externalId UUID generated by controller
     * @param seqNumber Generated by adapter
     * @param deviceId The UUID of device
     */
    public IpSecExternalIdMapping(String ipSecConnectionId, String externalId, String seqNumber, String deviceId) {
        super();
        this.ipSecConnectionId = ipSecConnectionId;
        this.externalId = externalId;
        this.seqNumber = seqNumber;
        this.deviceId = deviceId;
    }

    public String getIpSecConnectionId() {
        return ipSecConnectionId;
    }

    public void setIpSecConnectionId(String ipSecConnectionId) {
        this.ipSecConnectionId = ipSecConnectionId;
    }

    public String getExternalId() {
        return externalId;
    }

    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    public String getSeqNumber() {
        return seqNumber;
    }

    public void setSeqNumber(String seqNumber) {
        this.seqNumber = seqNumber;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
}
